### ISSUE TITLE
Error when running Box from PHAR file

### ISSUE THREAD

**Issue by Racso** [box-project/box#1008]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 4.3.8
| PHP version | PHP 8.1.6 (cli)
| Platform with version | Windows 10
| Github Repo | N/A

When trying to run Box.phar on Windows (from either Cmd or PowerShell) with a standard `php box.phar` command, I get this error twice:

```
C:\>php box.phar

PHP Fatal error:  Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, bool given in phar://C:/box.phar/.box/src/Terminal.php:60
Stack trace:
#0 phar://C:/box.phar/.box/src/Terminal.php(60): trim(false)
#1 phar://C:/box.phar/.box/src/Terminal.php(31): HumbugBox436\KevinGH\RequirementChecker\Terminal::initDimensions()
#2 phar://C:/box.phar/.box/src/Printer.php(28): HumbugBox436\KevinGH\RequirementChecker\Terminal->getWidth()
#3 phar://C:/box.phar/.box/src/Checker.php(17): HumbugBox436\KevinGH\RequirementChecker\Printer->__construct(32, true)
#4 phar://C:/box.phar/.box/bin/check-requirements.php(22): HumbugBox436\KevinGH\RequirementChecker\Checker::checkRequirements()
#5 C:\box.phar(16): require('phar://C:/box.p...')
#6 {main}
  thrown in phar://C:/box.phar/.box/src/Terminal.php on line 60
```

If installed with composer and run in a similar fasion (`php vendor/bin/box`), it works just fine.

Running other PHAR files works normally.

**Comment by Racso** [comment]
It seems that this is a duplicate of https://github.com/box-project/box/issues/1002, and that a fix is already on its way in https://github.com/box-project/box/pull/999.
