### ISSUE TITLE
UnexpectedValueException when invoking CLI via PHAR

### ISSUE THREAD

**Issue by raphaelstolt** [box-project/box#1046]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 4.3.8@5534406
| PHP version | 8.1.6
| Platform with version | Ubuntu 20.04.4 LTS
| Github Repo | [lean-package-validator](https://github.com/raphaelstolt/lean-package-validator)

After compiling a PHAR archive w/o any errors I get an error when running the compiled PHAR. Not sure if this is an Box or Symfony/Console problem.

<details>
 <summary>box.json.dist</summary>
 
 ```json
{
    "directories": ["src"],
    "finder": [
        {
            "name": "*.php",
            "exclude": ["tests", ".github", "example", ".*"],
            "in": "vendor"
         }
    ]
}
 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ bin/lean-package-validator.phar --version
 > PHP Fatal error:  Uncaught UnexpectedValueException: DirectoryIterator::__construct(phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/vendor/symfony/console/Command/../Resources/): Failed to open directory: operation failed in phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/vendor/symfony/console/Command/DumpCompletionCommand.php:152
Stack trace:
#0 phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/vendor/symfony/console/Command/DumpCompletionCommand.php(152): DirectoryIterator->__construct()
#1 phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/vendor/symfony/console/Command/DumpCompletionCommand.php(55): Symfony\Component\Console\Command\DumpCompletionCommand->getSupportedShells()
#2 phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/vendor/symfony/console/Command/Command.php(137): Symfony\Component\Console\Command\DumpCompletionCommand->configure()
#3 phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/vendor/symfony/console/Application.php(1136): Symfony\Component\Console\Command\Command->__construct()
#4 phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/vendor/symfony/console/Application.php(1312): Symfony\Component\Console\Application->getDefaultCommands()
#5 phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/vendor/symfony/console/Application.php(536): Symfony\Component\Console\Application->init()
#6 phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/vendor/symfony/console/Application.php(522): Symfony\Component\Console\Application->add()
#7 phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/bin/lean-package-validator(47): Symfony\Component\Console\Application->addCommands()
#8 /home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar(14): require('...')
#9 {main}
  thrown in phar:///home/vagrant/workspace/oss/lean-package-validator/bin/lean-package-validator.phar/vendor/symfony/console/Command/DumpCompletionCommand.php on line 152
 ```
</details>

**Comment by theofidry** [comment]
At first glance I would say this is a configuration thing: `DumpCompletionCommand` tries to access to the `Resource` directory which may not be present (did not double check). You can check this by either inspecting the PHAR in your IDE, extracting in a specific directory (`box extract`) or just inspect your PHAR directly `box info`.

If it is included, it could be that it's a `DumpCompletionCommand` issue. AFAIK Symfony is not always on top about making things PHAR compatible. They do accept fixes for such issues however. That said `box completion` does seem to work so I would be leaning towards the first point.

I would recommend something like this for your `box.json`:

```
{
  "$schema": "res/schema.json",

  "directories": ["path/to/Resources"],
  "force-autodiscovery": true
}
```

**Comment by raphaelstolt** [comment]
Altering my box.json.dist as suggested fixed my issue. Ta.
