### ISSUE TITLE
Box 3.15.0 Opis\Closure\SerializableClosure class not found with PhpScoper  PHP 8.1

### ISSUE THREAD

**Issue by alexander-schranz** [box-project/box#603]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.15.0 
| PHP version | 8.1.2 
| Platform with version | MacOS
| Github Repo | - 

If I'm updating from `3.14` to `3.15.0`.

And run `box compile`

I get the error that the class:

```bash
PHP Fatal error:  Uncaught Error: Class "Opis\Closure\SerializableClosure" not found in /Users/test/Documents/Projects/vendor-bin/box/vendor/humbug/php-scoper/vendor-hotfix/SimpleScoper.php:142
```

was not found.

<details>
 <summary>box.json.dist</summary>
 
 ```json
    "banner": [
        "My Banner"
    ],
    "alias": "test.phar",
    "algorithm": "OPENSSL",
    "key": "secrets/rsa.private",
    "compression": "GZ",
    "chmod": "0755",
    "directories": [],
    "files-bin": [
        "vendor/dbrekelmans/bdi/bdi.phar"
    ],
    "exclude-dev-files": false,
    "finder": [
        {
            "name": "*.php",
            "exclude": [
                ".git",
                "tests",
                "behat",
                "Tests",
                "phpspec",
                "mockery",
                "phpunit"
            ],
            "in": "vendor"
        }
    ],
    "compactors": [
        "KevinGH\\Box\\Compactor\\Json",
        "KevinGH\\Box\\Compactor\\Php",
        "KevinGH\\Box\\Compactor\\PhpScoper"
    ],
    "git-version": "package_version",
    "main": "bin/test",
    "output": "test.phar"
 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ box compile

PHP Fatal error:  Uncaught Error: Class "Opis\Closure\SerializableClosure" not found in /Users/test/Documents/Projects/vendor-bin/box/vendor/humbug/php-scoper/vendor-hotfix/SimpleScoper.php:142
Stack trace:
#0 [internal function]: KevinGH\Box\PhpScoper\SimpleScoper::KevinGH\Box\PhpScoper\{closure}(Object(Closure))
#1 /Users/test/Documents/Projects/test/vendor-bin/box/vendor/humbug/php-scoper/vendor-hotfix/SimpleScoper.php(144): array_map(Object(Closure), Array)
#2 /Users/test/Documents/Projects/test/vendor-bin/box/vendor/humbug/php-scoper/vendor-hotfix/SimpleScoper.php(52): KevinGH\Box\PhpScoper\SimpleScoper::createSerializablePatchers(Object(Humbug\PhpScoper\Patcher\PatcherChain))
#3 /Users/test/Documents/Projects/test/vendor-bin/box/vendor/humbug/php-scoper/vendor-hotfix/Configuration.php(2848): KevinGH\Box\PhpScoper\SimpleScoper->__construct(Object(Humbug\PhpScoper\Configuration\Configuration))
#4 /Users/test/Documents/Projects/test/vendor-bin/box/vendor/humbug/php-scoper/vendor-hotfix/Configuration.php(1864): KevinGH\Box\Configuration\Configuration::createPhpScoperCompactor(Object(stdClass), '/Users/alexande...', Object(KevinGH\Box\Configuration\ConfigurationLogger))
 ```
</details>

**Comment by theofidry** [comment]
See https://github.com/humbug/php-scoper/issues/642

Should be fixed shortly

**Comment by theofidry** [comment]
Should be fixed with https://github.com/box-project/box/releases/tag/3.16.0

**Comment by alexander-schranz** [comment]
@theofidry thank you!
