### ISSUE TITLE
Uncaught Exception: stream_select(): supplied resource is not a valid stream resource in {path}\vendor\amphp\amp\lib\Loop\NativeDriver.php:79

### ISSUE THREAD

**Issue by stevebauman** [box-project/box#648]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.16.0
| PHP version | 7.4 to 8.1
| Platform with version | Windows
| Github Repo | https://github.com/spatie/global-ray

When running `box compile` without the `--no-parallel` option on Windows, I receive the below exception:

<details>
 <summary>Configuration</summary>

```json
{
    "output": "ray.phar",
    "compactors": ["KevinGH\\Box\\Compactor\\PhpScoper"]
}
```
</details>

<details>
 <summary>Scoper Configuration</summary>

```php
<?php

return [
    'prefix' => 'GlobalRay',
    'expose-functions' => ['ray', 'rd'],
];
```
</details>

<details>
 <summary>Exception Stack Trace</summary>
 
 ```text
> vendor/bin/box compile

____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 3.[16](https://github.com/spatie/global-ray/runs/5352303978?check_suite_focus=true#step:6:16).0@adb[28](https://github.com/spatie/global-ray/runs/5352303978?check_suite_focus=true#step:6:28)2a

 // Loading the configuration file "D:\a\global-ray\global-ray\ray-phar-generator\box.json".                           

🔨  Building the PHAR "D:/a/global-ray/global-ray/ray-phar-generator/ray.phar"

? Registering compactors
  + KevinGH\Box\Compactor\PhpScoper
? Adding main file: D:/a/global-ray/global-ray/ray-phar-generator/index.php
? Adding requirements checker
? Adding binary files
    > No file found
? Auto-discover files? Yes
? Exclude dev files? Yes
? Adding files

PHP Fatal error:  Uncaught Exception: stream_select(): supplied resource is not a valid stream resource in D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\amp\lib\Loop\NativeDriver.php:79
Stack trace:
#0 [internal function]: Amp\Loop\NativeDriver->Amp\Loop\{closure}()
#1 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\amp\lib\Loop\NativeDriver.php(300): stream_select()
#2 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\amp\lib\Loop\NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams()
#3 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\amp\lib\Loop\Driver.php(1[38](https://github.com/spatie/global-ray/runs/5352303978?check_suite_focus=true#step:6:38)): Amp\Loop\NativeDriver->dispatch()
#4 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\amp\lib\Loop\Driver.php(72): Amp\Loop\Driver->tick()
#5 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\amp\lib\Loop.php(95): Amp\Loop\Driver->run()
#6 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\amp\lib\functions.php(229): Amp\Loop::run()
#7 D:\a\global-ray\global-ray\ray-phar-generator\vendor\h in D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\amp\lib\functions.php on line 231
PHP Fatal error:  Uncaught ErrorException: fclose(): supplied resource is not a valid stream resource in D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\process\lib\Internal\Windows\SocketConnector.php:70
Stack trace:
#0 [internal function]: KevinGH\Box\{closure}()
#1 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\process\lib\Internal\Windows\SocketConnector.php(70): fclose()
#2 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\process\lib\Internal\Windows\Runner.php(183): Amp\Process\Internal\Windows\SocketConnector->failHandleStart()
#3 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\process\lib\Process.php(141): Amp\Process\Internal\Windows\Runner->kill()
#4 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\parallel\lib\Context\Process.php([39](https://github.com/spatie/global-ray/runs/5352303978?check_suite_focus=true#step:6:39)5): Amp\Process\Process->kill()
#5 D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\parallel\lib\Worker\Internal\WorkerProcess.php(57): Amp\Parallel\Context\Process->kill()
#6 D:\a\global-ray\global-ray\ray-phar-generator\ven in D:\a\global-ray\global-ray\ray-phar-generator\vendor\amphp\process\lib\Internal\Windows\SocketConnector.php on line 70
Script vendor/bin/box compile handling the build event returned with error code 255
 ```
</details>

You can see the details in this run here:

https://github.com/spatie/global-ray/runs/5352303978?check_suite_focus=true

When I added the `--no-parellel` option, the exception went away. This is only an issue with Windows, as no exception is generated on Linux. The exception can be reproduced on PHP 7.4, 8.0 and 8.1.

Let me know if you require any further information. Thanks for your time and for this awesome project! 🙏

**Comment by theofidry** [comment]
Thanks for the report!

Box usage of AMPHP is very limited as you can see here: https://github.com/box-project/box/blob/master/src/Box.php#L435

So I would tend to say if there is an issue, it is more likely to be either be straight up a problem with AMPHP code or due to the fact (and arguably it is a lot more edge case from AMPHP perspective) that it is executed from within a PHAR.

@kelunik do you have any idea if AMPHP is supposed to work fine on Windows?

**Comment by theofidry** [comment]
I'll be closing this as there is no more actionable here unfortunately :(

**Comment by kelunik** [comment]
@theofidry Seems like I missed this. Yes, it's supposed to work fine on Windows. Stream watchers must be disabled before resources are closed, which is likely not the case here.

**Comment by theofidry** [comment]
>Stream watchers must be disabled before resources are closed, which is likely not the case here.

Sorry what are those? ^^ As you can see I'm merely using `parallelMap()` so I don't know if there is much I can do?
