### ISSUE TITLE
Composer installation does not work when following docs

### ISSUE THREAD

**Issue by Zegnat** [box-project/box#697]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 4.0.2 (`composer bin all show \| grep humbug/box`)
| PHP version | 8.1.10
| Composer version | 2.4.1
| Platform with version | macOS 12.5.1

Running `vendor/bin/box` will throw an Exception and the application cannot be used after following [the Installation documentation for Composer](https://box-project.github.io/box/installation/#composer).

Quick reproduction steps:
```bash
# Clean folder and composer.json
cd `mktemp -d -t 'box'`
composer init --no-interaction --name zegnat/test
composer config allow-plugins.bamarni/composer-bin-plugin true
# Recommended installation steps
composer require --dev bamarni/composer-bin-plugin
composer bin box require --dev humbug/box
```

<details>
 <summary>Output</summary>
 
 ```bash
bash-5.1$ vendor/bin/box
PHP Fatal error:  Uncaught ErrorException: require_once(/private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/../vendor/composer/InstalledVersions.php): Failed to open stream: No such file or directory in /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/functions.php:61
Stack trace:
#0 /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/functions.php(61): KevinGH\Box\{closure}(2, 'require_once(/p...', '/private/var/fo...', 61)
#1 /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/functions.php(61): require_once()
#2 /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/Console/Application.php(40): KevinGH\Box\get_box_version()
#3 /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/bin/box(58): KevinGH\Box\Console\Application->__construct()
#4 /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor/bin/box(120): include('/private/var/fo...')
#5 {main}
  thrown in /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/functions.php on line 61

Fatal error: Uncaught ErrorException: require_once(/private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/../vendor/composer/InstalledVersions.php): Failed to open stream: No such file or directory in /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/functions.php:61
Stack trace:
#0 /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/functions.php(61): KevinGH\Box\{closure}(2, 'require_once(/p...', '/private/var/fo...', 61)
#1 /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/functions.php(61): require_once()
#2 /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/Console/Application.php(40): KevinGH\Box\get_box_version()
#3 /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/bin/box(58): KevinGH\Box\Console\Application->__construct()
#4 /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor/bin/box(120): include('/private/var/fo...')
#5 {main}
  thrown in /private/var/folders/pv/rtwt6lqx2qn6fh2q3hpdf8m80000gn/T/box.rlqO4ObV/vendor-bin/box/vendor/humbug/box/src/functions.php on line 61
 ```
</details>

**Comment by Zegnat** [comment]
Just realised there is already a PR for: https://github.com/box-project/box/pull/695. But I could not find an issue?

Feel free to close this in favour of the PR, or keep it around until the PR gets merged so others have an easier time finding it.

**Comment by theofidry** [comment]
Thanks for the report! Will be fixed in the next release
