### ISSUE TITLE
Cannot compile PHAR when box is a dependency of user project

### ISSUE THREAD

**Issue by llaville** [box-project/box#924]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 4.3.7
| PHP version | 8.1.16
| Platform with version | Ubuntu 22.04.2 LTS on WSL2
| Github Repo | none

<details>
 <summary>box.json.dist</summary>
 
 ```json
{
    "main": false,
    "output": "sandbox.phar",
    "directories": ["vendor"],
    "directories-bin": ["vendor/humbug/box/res/requirement-checker"],
    "compression": "GZ",
    "metadata": ""
}
 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ vendor/bin/box compile -vvv
 > output
[debug] Current memory limit: "512MB"
[debug] Checking BOX_ALLOW_XDEBUG
[debug] phar.readonly is enabled
[debug] The Xdebug extension is loaded (3.2.0) xdebug.mode=off
[debug] Configured `phar.readonly=0`
[debug] Process restarting (BOX_ALLOW_XDEBUG=internal|3.2.0|1|*|*)
[debug] Running /usr/local/bin/php vendor/bin/box compile -vvv
[debug] Current memory limit: "512MB"
[debug] Checking BOX_ALLOW_XDEBUG
[debug] Restarted (77 ms). The Xdebug extension is not loaded

    ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 4.3.7@e89dfe8

 // Loading the configuration file "/shared/backups/forks/box-4.3/box.json.dist".


Fatal error: Uncaught Error: Call to undefined method KevinGH\Box\Configuration\Configuration::setComposerBin() in /shared/backups/forks/box-4.3/vendor/humbug/box/src/Console/Command/Compile.php:209
Stack trace:
#0 /shared/backups/forks/box-4.3/vendor/fidry/console/src/Command/SymfonyCommand.php(93): KevinGH\Box\Console\Command\Compile->execute(Object(Fidry\Console\Input\IO))
#1 /shared/backups/forks/box-4.3/vendor/symfony/console/Command/Command.php(312): Fidry\Console\Command\SymfonyCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /shared/backups/forks/box-4.3/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /shared/backups/forks/box-4.3/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Fidry\Console\Command\SymfonyCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /shared/backups/forks/box-4.3/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /shared/backups/forks/box-4.3/vendor/fidry/console/src/Application/ApplicationRunner.php(66): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /shared/backups/forks/box-4.3/vendor/humbug/box/bin/box(60): Fidry\Console\Application\ApplicationRunner->run(Object(Fidry\Console\Input\IO))
#7 /shared/backups/forks/box-4.3/vendor/bin/box(120): include('/shared/backups...')
#8 {main}
  thrown in /shared/backups/forks/box-4.3/vendor/humbug/box/src/Console/Command/Compile.php on line 209
[debug] Restarted process exited 255
 ```
</details>

From an empty directory : install box 4.3 with `composer require humbug/box ^4.3` 

Getting 

<details>
 <summary>composer.json</summary>
 
 ```json
{
    "require": {
        "humbug/box": "^4.3"
    }
}
 ```
</details>

And directory contents

```
drwxr-xr-x 19 devilbox devilbox   4096 Mar  9 13:08 vendor/
-rw-r--r--  1 devilbox devilbox    198 Mar  9 15:27 box.json.dist
-rw-r--r--  1 devilbox devilbox    143 Mar  9 15:31 composer.json
-rw-r--r--  1 devilbox devilbox 111388 Mar  9 13:08 composer.lock
```

**Comment by llaville** [comment]
@theofidry Good New, I've found origin of issue.

Look into `vendor/composer/autoload_classmap.php`, and we will find that 

```
'KevinGH\\Box\\Configuration\\Configuration' => $vendorDir . '/humbug/php-scoper/vendor-hotfix/Configuration.php',
```

But this version https://github.com/humbug/php-scoper/blob/0.18.2/vendor-hotfix/Configuration.php did not included missing methods introduced by feature https://github.com/box-project/box/issues/721

When I removed this entry from `autoload_classmap.php`, I should be able to compile from a locally installation !

**Comment by llaville** [comment]
> When I removed this entry from `autoload_classmap.php`, I should be able to compile from a locally installation !

**To avoid confusion for all audience, this is just a workaround, not a fix**, because this file is part of Composer and will be regenerated each time we run `composer update` or `composer dump-autoload` commands.

**Comment by theofidry** [comment]
yeah this vendor-hotfix needs to go away. It's a temporary measure since Box & PHP-Scoper are cyclic dependencies. PHP-Scoper can be updated to remove those vendor-hotfix right now though (I think)

**Comment by llaville** [comment]
@theofidry Just tested the `4.3.8` and run in trouble until I understand that I MUST declare the "vendor/humbug/php-scoper/vendor-hotfix/.gitkeep" in my own local box config file otherwise it won't work !

```text
Box version 4.3.8@5534406

 // Loading the configuration file "/shared/backups/bartlett/box-manifest/box.json.dist".

🔨  Building the PHAR "/shared/backups/bartlett/box-manifest/bin/box-manifest.phar"

? Removing the existing PHAR "/shared/backups/bartlett/box-manifest/bin/box-manifest.phar"
? Checking Composer compatibility
    > Supported version detected
? Setting replacement values
  + @git-version@: 2.3.1-36-gb526ccc
? No compactor to register
? Adding main file: /shared/backups/bartlett/box-manifest/bin/box-manifest
? Adding requirements checker
? Adding binary files
    > 36 file(s)
? Auto-discover files? No
? Exclude dev files? Yes
? Adding files
    > 3425 file(s)
? Generating new stub
  - Using shebang line: #!/usr/bin/env php
  - Using banner:
    > Generated by Humbug Box 4.3.8@5534406.
    >
    > @link https://github.com/humbug/box
? Dumping the Composer autoloader

In ComposerOrchestrator.php line 207:

  Could not dump the autoloader.


In ComposerOrchestrator.php line 210:

  The command "'/usr/local/bin/composer' 'dump-autoload' '--classmap-authoritative' '--no-dev' '--ansi'" failed.

  Exit Code: 1(General error)

  Working directory: /tmp/box/Box58123

  Output:
  ================
  Generating optimized autoload files (authoritative)


  Error Output:
  ================

  In ClassMapGenerator.php line 129:


    Could not scan for classes inside "/tmp/box/Box58123/vendor/humbug/php-scoper/vendor-hotfix/" which does not appear to be a file
  nor a fold
    er




  dump-autoload [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--apcu-prefix APCU-PREFIX] [--dev] [--no-dev] [--ignore-platform
  -req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--strict-psr]


compile [--debug] [--no-parallel] [--no-restart] [--dev] [--no-config] [--with-docker] [--composer-bin COMPOSER-BIN] [--allow-composer-check-failure] [-c|--config CONFIG] [-d|--working-dir WORKING-DIR]

```

**Comment by theofidry** [comment]
@llaville it's something I find a bit annoying but not sure on how to fix it.

The problem is that php-scoper has this `vendor-hotfix` directory which, when unused, only contains `.gitkeep`. However, Box removes dotfiles so you end up with an empty `vendor-hotfix` directory which appears to be a problem for some reasons (not sure why, but I think it's on Composer side).

In practice I don't expect it to be a problem unless you ship Box within your PHAR (which you are doing but I expect it to be an edge case).

So it's either that or constantly removing/adding `vendor-hotfix` to PHP-Scoper :/

**Comment by llaville** [comment]
> In practice I don't expect it to be a problem unless you ship Box within your PHAR (which you are doing but I expect it to be very rare).
> 
> So it's either that or constantly removing/adding `vendor-hotfix` to PHP-Scoper :/

👍 But it should be clarified identified in the documentation, otherwise we will forgot what to do !
