### ISSUE TITLE
Project with aws php sdk cannot be built

### ISSUE THREAD

**Issue by magnetik** [box-project/box#992]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 4.3.8 
| PHP version | 8.1 (or 8.2)
| Platform with version | Ubuntu
| Github Repo | - 

After using box 3.x for years, I just switched to 4.3.8.

The compile worked flawlessly, but when executing the phar, this error showed up:

` Failed to open stream: phar error: internal corruption of phar "myPhar" (actual filesize mismatch on file "vendor/aws/aws-sdk-php/src/data/endpoints.json.php") `

I've removed all options (I was suspecting the BZ2 compression) and still have this error. 

The composer.json of the project is:
```
{
    "autoload": {
        "psr-4": {
            "": "src/"
        }
    },
    "require": {
        "php": "^7.3 || ^8.0",
        "mnapoli/silly": "^1.6",
        "aws/aws-sdk-php": "~3.17",
        "symfony/yaml": "^6.2"
    }
}
```

**Comment by magnetik** [comment]
Nevermind, it was probably a problem with the shared folder in my VM. 

Thanks to all the maintainers for this project ❤️ !

**Comment by magnetik** [comment]
Nevermind. I've added a repro here : https://github.com/magnetik/repro-bug-box

The output of "make" is: 

```
> % make                                                                                  [master]
box compile

    ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 4.3.8@5534406 2023-03-17 08:56:09 UTC

 // Loading the configuration file "/vagrant/lab/repro-bug-box/box.json".

🔨  Building the PHAR "/tmp/binary.phar"

? Removing the existing PHAR "/tmp/binary.phar"
? Checking Composer compatibility
    > Supported version detected
? No compactor to register
? Adding main file: /vagrant/lab/repro-bug-box/bin/binary
? Adding requirements checker
? Adding binary files
    > No file found
? Auto-discover files? Yes
? Exclude dev files? Yes
? Adding files
    > 2496 file(s)
? Generating new stub
  - Using shebang line: #!/usr/bin/env php
  - Using banner:
    > Generated by Humbug Box 4.3.8@5534406.
    >
    > @link https://github.com/humbug/box
? Dumping the Composer autoloader
? Removing the Composer dump artefacts
? Compressing with the algorithm "BZ2"
    > Warning: the extension "bz2" will now be required to execute the PHAR
? Setting file permissions to 0755
* Done.

💡  1 recommendation found:
    - The "chmod" setting can be omitted since is set to its default value
No warning found.

 // PHAR: 2529 files (3.59MB)
 // You can inspect the generated PHAR with the "info" command.

 // Memory usage: 69.57MB (peak: 72.95MB), time: 57secs

/tmp/binary.phar
PHP Warning:  include(phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/../data/endpoints.json.php): Failed to open stream: phar error: internal corruption of phar "/tmp/binary.phar" (actual filesize mismatch on file "vendor/aws/aws-sdk-php/src/data/endpoints.json.php") in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/functions.php on line 151

Warning: include(phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/../data/endpoints.json.php): Failed to open stream: phar error: internal corruption of phar "/tmp/binary.phar" (actual filesize mismatch on file "vendor/aws/aws-sdk-php/src/data/endpoints.json.php") in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/functions.php on line 151
PHP Warning:  include(): Failed opening 'phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/../data/endpoints.json.php' for inclusion (include_path='.:/usr/share/php') in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/functions.php on line 151

Warning: include(): Failed opening 'phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/../data/endpoints.json.php' for inclusion (include_path='.:/usr/share/php') in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/functions.php on line 151
PHP Warning:  Trying to access array offset on value of type bool in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php on line 115

Warning: Trying to access array offset on value of type bool in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php on line 115
PHP Warning:  foreach() argument must be of type array|object, null given in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php on line 115

Warning: foreach() argument must be of type array|object, null given in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php on line 115
PHP Warning:  Trying to access array offset on value of type bool in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php on line 101

Warning: Trying to access array offset on value of type bool in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php on line 101
PHP Fatal error:  Uncaught TypeError: Aws\Endpoint\PartitionEndpointProvider::__construct(): Argument #1 ($partitions) must be of type array, null given, called in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php on line 101 and defined in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php:29
Stack trace:
#0 phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php(101): Aws\Endpoint\PartitionEndpointProvider->__construct()
#1 phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/ClientResolver.php(656): Aws\Endpoint\PartitionEndpointProvider::defaultProvider()
#2 phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/ClientResolver.php(370): Aws\ClientResolver::_apply_endpoint_provider()
#3 phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/AwsClient.php(221): Aws\ClientResolver->resolve()
#4 phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Ec2/Ec2Client.php(1217): Aws\AwsClient->__construct()
#5 phar:///tmp/binary.phar/bin/binary(5): Aws\Ec2\Ec2Client->__construct()
#6 /tmp/binary.phar(14): require('...')
#7 {main}
  thrown in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php on line 29

Fatal error: Uncaught TypeError: Aws\Endpoint\PartitionEndpointProvider::__construct(): Argument #1 ($partitions) must be of type array, null given, called in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php on line 101 and defined in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php:29
Stack trace:
#0 phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php(101): Aws\Endpoint\PartitionEndpointProvider->__construct()
#1 phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/ClientResolver.php(656): Aws\Endpoint\PartitionEndpointProvider::defaultProvider()
#2 phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/ClientResolver.php(370): Aws\ClientResolver::_apply_endpoint_provider()
#3 phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/AwsClient.php(221): Aws\ClientResolver->resolve()
#4 phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Ec2/Ec2Client.php(1217): Aws\AwsClient->__construct()
#5 phar:///tmp/binary.phar/bin/binary(5): Aws\Ec2\Ec2Client->__construct()
#6 /tmp/binary.phar(14): require('...')
#7 {main}
  thrown in phar:///tmp/binary.phar/vendor/aws/aws-sdk-php/src/Endpoint/PartitionEndpointProvider.php on line 29
make: *** [Makefile:2: repro] Error 255
```

**Comment by theofidry** [comment]
Sorry for the very late reply, do you have a reproducer by any chance?

**Comment by magnetik** [comment]
No problem ! The reproducer is indeed available in a previous comment : https://github.com/magnetik/repro-bug-box

**Comment by theofidry** [comment]
Is there any way to get the content of `endpoints.json.php`?

>It seems to be related to the BZ2 compression. it works fine with BZ

Does that mean that even with the previous system and compression you are getting the same error?
